// vue-app/src/App.vue
<script setup>

import DataTable from "./components/DataTable.vue";
import { onMounted, ref } from "vue";

const weatherData = ref([]);

//Fetch data from json file
onMounted(async () => {
  const response = await fetch("/StockholmHistoricalWeatherObservations.json");
  weatherData.value = await response.json();
});

</script>

<template>
  <div >
  <h1> Data Table</h1>
   <DataTable :weatherData="weatherData" />
  </div>
</template>

// svelte-app/src/App.svelte
<script>

  import DataTable from './lib/DataTable.svelte';
  import { onMount } from 'svelte';
  
  let weatherData = []
  
  //Fetch data from json file
  onMount(async () => {
    const res = await fetch('./StockholmHistoricalWeatherObservations.json');
    weatherData = await res.json();
  })

</script>

<div>
  <h1> Data Table</h1>
   <DataTable {weatherData} />
</div>
